name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit-hooks:
    name: Check that pre-commit hooks pass
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v4
      - name: python environment step
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install pre-commit
        run: python3 -m pip install pre-commit
      - id: changed-files
        name: identify modified files
        uses: tj-actions/changed-files@v44
      - name: run pre-commit hooks on modified files
        run: pre-commit run --color always --files ${{ steps.changed-files.outputs.all_changed_files }} --show-diff-on-failure
